import os
import anthropic
from anthropic import AnthropicBedrock
import time

# Function to analyze a company's financial reports and generate insights
def analyze_company_financials(company_path):
    # Create an instance of the AnthropicBedrock client
    client = AnthropicBedrock(
        aws_access_key="",  # Removed for security reasons, in production I would use an environment variable
        aws_secret_key="",  # Removed for security reasons, in production I would use an environment variable
        aws_region="us-east-1",
    )

    # Get the company name from the path
    company_name = company_path.split('/')[0]

    # Iterate through each year folder in the company's path
    for year_folder in os.listdir(company_path):
        year = year_folder.split('-')[1]
        section_file_path = os.path.join(company_path, year_folder, 'section 8 Text.txt')
        full_submission_file_path = os.path.join(company_path, year_folder, 'full-submission.txt')

        # Check if the 'section 8 Text.txt' file exists, and read its contents
        if os.path.exists(section_file_path):
            with open(section_file_path, 'r', encoding='utf-8') as file:
                data = file.read()
        # If the 'section 8 Text.txt' file doesn't exist, read the 'full-submission.txt' file instead
        elif os.path.exists(full_submission_file_path):
            with open(full_submission_file_path, 'r', encoding='utf-8') as file:
                data = file.read()

        print(f"Generating insights for {company_name} in year {year}:")

        # Create a message using the AnthropicBedrock client
        message = client.messages.create(
            model="anthropic.claude-3-haiku-20240307-v1:0",
            max_tokens=1000,
            temperature=0,
            system=data,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "From this report. All I want you is to tell me on separate lines the net income as 'Net Income: $XXX' and the operating income as 'Operating Income: $XXX'. If any of these values are at a loss, add a negative sign to the number, but the data should strictly follow this template. and then give me a summary of the company's overall financial health as 'Summary: ', feel free to cite metrics for the summary and use the full data provided in the report to draw conclusions and point out insights. Provide justification backed by the data for claims made in the summary."
                        }
                    ]
                }
            ]
        )

        # Write the insights generated by Claude to a file
        insights_file_path = os.path.join(company_path, year_folder, 'insights.txt')
        with open(insights_file_path, 'w') as file:
            file.write('\n'.join([block.text for block in message.content]))

        print("Done with year", year)
        time.sleep(2)  # To avoid rate limiting

# Dictionary to map ticker symbols to company names
ticker_to_name = {"AAPL": "Apple", "MSFT": "Microsoft"}

# Analyze the financials for each ticker symbol
for ticker in ticker_to_name:
    path = f"{ticker_to_name[ticker]}/sec-edgar-filings/{ticker}/10-K"
    analyze_company_financials(path)

